apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: registry.vmsalem.local/tbs-workload/aspnet:b1.20200708.162626
        name: nodejs
        ports:
        - containerPort: 8080      
