apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: aspnet
  template:
    metadata:
      labels:
        app: aspnet
    spec:
      containers:
      - image: vmsalem/aspnet:b2.20200726.131529
      # - image: registry.vmsalem.local/tbs-workload/dotnet:b8.20200726.112714
        name: aspnet
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080" 
