apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - image: harbor.vmsalem.local/tbs-deploy/petclinic:b2.20200927.200349
        name: petclinic
        ports:
        - containerPort: 8080        
