apiVersion: apps/v1
kind: Deployment
metadata:
  name: devstack
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: vmsalem/nodejs2:b1.20200528.153454
        name: nodejs
        ports:
        - containerPort: 8000      
