apiVersion: apps/v1
kind: Deployment
metadata:
  name: devstack
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: registry.vmsalem.local/tbs-workload/nodejs-web:b3.20200706.211234
        name: nodejs
        ports:
        - containerPort: 8000      
